spring:
  profiles:
    active: local
    include: swagger
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false # we use gulp + BrowserSync for livereload
  jackson:
    serialization.indent_output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3706/pangolin_fplms_test?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2b8
    name:
    username: root
    password: 123456
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximumPoolSize: 50
  rabbitmq:
    username: flpms
    password: flpms
    host: 192.168.3.2
    virtual-host: flpms
    port: 5672
  redis:
    database: 10
    host: 192.168.3.3
    port: 6479
  boot:
    admin:
      client:
        url: http://localhost:1996
  jpa:
    #    hibernate:
    #     ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 250
      hibernate.jdbc.time_zone: Asia/Shanghai
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
file:
  dir: /usr/local/files
  base-url: http://192.168.3.3:1990/common-service/api/uploadFileController/getFileStreamById
eureka:
  instance:
    hostname: common-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1995/eureka/
server:
  port: 1994
