spring:
  profiles:
    active: demo
    include: swagger
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false # we use gulp + BrowserSync for livereload
  jackson:
    serialization.indent_output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.60.107:3306/pangolin_financial?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2b8
    name:
    username: demouser
    password: demomysql!olap
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximumPoolSize: 50
  rabbitmq:
    username: zwuser
    password: Zhiwang.123
    host: 192.168.60.107
    virtual-host: /
    port: 5672
  redis:
    database: 1
    host: 192.168.60.107
    port: 6379
    password: zhiwang.123
  boot:
    admin:
      client:
        url: http://localhost:8762
  jpa:
    #    hibernate:
    #     ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 250
      hibernate.jdbc.time_zone: Asia/Shanghai
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
file:
  dir: /usr/local/files
  base-url: http://47.100.195.197:9999/common-service/api/uploadFileController/getFileStreamById
eureka:
  instance:
    hostname: common-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9004
