spring:
  profiles:
    active: prod
    include: swagger
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false # we use gulp + BrowserSync for livereload
  jackson:
    serialization.indent_output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/pangolin_fplms?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2b8
    name:
    username: root
    password: Cheyun_123456
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximumPoolSize: 50
  rabbitmq:
    username: admin
    password: admin
    host: localhost
    virtual-host: admin
    port: 5672
  redis:
    database: 0
    host: localhost
    port: 6379
    password: yunche2020
  boot:
    admin:
      client:
        url: http://localhost:8762
  jpa:
    #    hibernate:
    #     ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 250
      hibernate.jdbc.time_zone: Asia/Shanghai
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
file:
  dir: /usr/local/files
  base-url: http://47.111.188.145:9000/common-service/api/uploadFileController/getFileStreamById
eureka:
  instance:
    hostname: common-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9004
  tomcat:
    basedir: /tomcat/tmp
