spring:
  profiles:
    include: swagger
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false # we use gulp + BrowserSync for livereload
  jackson:
    serialization.indent_output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.3.3:3306/yunche_test?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2b8
    name:
    username: root
    password: 123456
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximumPoolSize: 50
  rabbitmq:
    username: yunche
    password: 123456
    host: 192.168.3.2
    virtual-host: yunche
    port: 5672
  redis:
    database: 10
    host: 192.168.3.2
    port: 6379
    password: redis123456
  boot:
    admin:
      client:
        url: http://localhost:10762
  jpa:
    #    hibernate:
    #     ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 250
      hibernate.jdbc.time_zone: Asia/Shanghai
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
file:
  dir: /usr/local/files
  base-url: http://117.36.75.166:9090/common-service/api/uploadFileController/getFileStreamById
eureka:
  instance:
    hostname: common-service
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:10761/eureka/
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
server:
  port: 10004
  tomcat:
    basedir: /tomcat/tmp